version: '3'

services:
  lb:
    image: openresty/openresty:alpine
    links:
      - cache
    volumes:
      - "./nginx-lb.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./load-balancer.lua:/usr/local/openresty/nginx/conf/load-balancer.lua"
    ports:
      - "80:8080"
    depends_on:
      - cache
      - redis
    environment:
      LB_ALGORITM: "${LB_ALGORITM}"

  cache:
    image: openresty/openresty:alpine
    links:
      - origin:origin
    volumes:
      - "./nginx-cache.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    ports:
      - "${CACHE_PORTS_RANGE}:8080"
    depends_on:
      - origin

  origin:
    build: ./origin
    ports:
      - "8080:8080"

  redis:
    image: redis
    ports:
      - "6379:6379"

  healthchecker:
    image: golang:1.12
    volumes:
      - ./healthchecker:/app
    working_dir: /app
    command: sh -c 'go build healthchecker.go && ./healthchecker'
    network_mode: "host"
    depends_on:
      - cache
      - redis
    environment:
      CACHE_PORTS_RANGE: "${CACHE_PORTS_RANGE}"
