version: '3'

services:
  lb:
    image: openresty/openresty:alpine
    links:
      - cache
    volumes:
      - "./nginx-lb.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    ports:
      - "80:8080"
    depends_on:
      - cache
  cache:
    image: openresty/openresty:alpine
    links:
      - origin:origin
    volumes:
      - "./nginx-cache.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    ports:
      - "8080"
    depends_on:
      - origin
  origin:
    build: .
    ports:
      - "8080:8080"
