version: '3'

services:
  lb:
    image: openresty/openresty:alpine
    links:
      - cache
    volumes:
      - "./nginx-lb.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./load-balancer.lua:/usr/local/openresty/nginx/conf/load-balancer.lua"
    ports:
      - "80:8080"
    depends_on:
      - cache
      - redis
  cache:
    image: openresty/openresty:alpine
    links:
      - origin:origin
    volumes:
      - "./nginx-cache.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    ports:
      - "8090-8099:8080"
    depends_on:
      - origin
  origin:
    build: ./origin
    ports:
      - "8080:8080"
  redis:
    image: redis
